import type { Row } from "@/lib/types";

export const NUMERIC_FIELDS = [
  "thi_phan_co_so",
  "thi_phan_cn",
  "thi_phan_ds",
  "gtgd_cs_ssi",
  "thanh_khoan_ttcs",
  "tong_du_no_margin",
  "slkh_margin",
  "du_no_t7",
  "slkh_t7",
  "du_no_trading_plus",
  "slkh_trading_plus",
  "slkh_register_mplus",
  "slkh_active_mplus",
  "du_no_mplus",
  "slkh_co_du_no_mplus",
  "giai_ngan_mplus",
  "slkh_giai_ngan_mplus",
  "du_no_spv",
  "ty_trong_spv",
  "thi_phan_phai_sinh",
  "thanh_khoan_tt_ps",
  "slkh_ps",
  "ty_le_slhd_dplus",
  "slkh_dplus",
  "ty_le_slkh_dplus",
  "kh_cancel_dplus",
  "kh_register_dplus",
  "kh_giu_qua_dem",
  "kh_sd_dplus",
  "slhd_giu_qua_dem",
  "du_no_dplus_giai_ngan",
  "du_no_dplus_cuoi_ngay",
  "so_du_scash",
  "so_du_casa_scash",
  "ty_le_scash_casa",
  "slkh_scash",
  "so_du_sfund",
  "slkh_sfund",
  "slkh_mo_moi",
] as const satisfies ReadonlyArray<keyof Row>;

export const PERCENT_FIELDS = new Set<keyof Row>([
  "thi_phan_co_so",
  "thi_phan_cn",
  "thi_phan_ds",
  "ty_trong_spv",
  "thi_phan_phai_sinh",
  "ty_le_slhd_dplus",
  "ty_le_slkh_dplus",
  "ty_le_scash_casa",
]);

export const FIELD_LABELS: Record<keyof Row, string> = {
  id: "ID",
  ngay: "Ngày",
  thi_phan_co_so: "Thị Phần HOSE",
  thi_phan_cn: "Thị Phần CN",
  thi_phan_ds: "Thị Phần DS",
  gtgd_cs_ssi: "GTGD Cơ Sở SSI",
  thanh_khoan_ttcs: "Thanh Khoản TTCS",
  tong_du_no_margin: "Tổng Dư Nợ Margin",
  slkh_margin: "SLKH Margin",
  du_no_t7: "Dư Nợ T7",
  slkh_t7: "SLKH T7",
  du_no_trading_plus: "Dư Nợ Trading+",
  slkh_trading_plus: "SLKH Trading+",
  slkh_register_mplus: "SLKH Register M+",
  slkh_active_mplus: "SLKH Active M+",
  du_no_mplus: "Dư Nợ M+",
  slkh_co_du_no_mplus: "SLKH Có Dư Nợ M+",
  giai_ngan_mplus: "Giải Ngân M+",
  slkh_giai_ngan_mplus: "SLKH Giải Ngân M+",
  du_no_spv: "Dư Nợ SPV",
  ty_trong_spv: "Tỷ Trọng SPV",
  thi_phan_phai_sinh: "Thị Phần Phái Sinh",
  thanh_khoan_tt_ps: "Thanh Khoản TTPS",
  slkh_ps: "SLKH Phái Sinh",
  ty_le_slhd_dplus: "Tỷ Lệ SLHĐ D+",
  slkh_dplus: "SLKH D+",
  ty_le_slkh_dplus: "Tỷ Lệ SLKH D+",
  kh_cancel_dplus: "KH Cancel D+",
  kh_register_dplus: "KH Register D+",
  kh_giu_qua_dem: "KH Giữ Qua Đêm",
  kh_sd_dplus: "KH Sử Dụng D+",
  slhd_giu_qua_dem: "SLHĐ Giữ Qua Đêm",
  du_no_dplus_giai_ngan: "Dư Nợ D+ Giải Ngân",
  du_no_dplus_cuoi_ngay: "Dư Nợ D+ Cuối Ngày",
  so_du_scash: "Số Dư S-Cash",
  so_du_casa_scash: "Số Dư CASA S-Cash",
  ty_le_scash_casa: "Tỷ Lệ S-Cash/CASA",
  slkh_scash: "SLKH S-Cash",
  so_du_sfund: "Số Dư S-Fund",
  slkh_sfund: "SLKH S-Fund",
  slkh_mo_moi: "SLKH Mở Mới",
  pushed_at: "Pushed At",
};
